### PR TITLE
Update style.css: Fixed margin

### PR DESCRIPTION
**Pull request by 0xScratch**
Button 'show & hide details' wasn't aligned well..

Before changes:
Screenshot (56)

After changes:
Screenshot (57)

### CODE REVIEW

**Comment by AnkushjainAj** [comment]
It's a very minor change.. Plz provide some valuable changes show your creativity

**Comment by 0xScratch** [comment]
Well, It's not for any hacktoberfest thing...I already completed that 2 weeks ago. This PR was just for some fixes not for adding any kind of feature. 
It be better if other contributors (those who haven't started their hacktoberfest journey) pick this repo up!

**Comment by AnkushjainAj** [comment]
I think if you complete hacktoberfest.. So you don't changes a cheap
changes in website and apply for merge request... What is this? Only margin
increase.. This is your contributions 😂

**Comment by 0xScratch** [comment]
You really need to be a better maintainer dude. Just saw your repo that time and thought of what's going on here...Opening that site left me uninterested tho. But on seeing that `button` error...was like "Oh this guy is careless enough to not even getting his margins right...let's just push a PR". But yea, now that looks like a mistake..cuz this person seeks some grand level contributions on a repo which isn't even maintained well 🤣🤣
Btw, check once again whether you are scamming other beginner level open-source contributors or not..cuz I feel these type of repositories don't really add up in hacktoberfest..and if these PRs from your repo are taking some space in hacktoberfest...you are lucky for some fact.
Closing this one, either someone else will fix these margins or who knows even you 😂
Thanks!

**Comment by AnkushjainAj** [comment]
Thanks for some non valuable suggestions 🤣😂

**Comment by AnkushjainAj** [comment]
I think you making fool as a open contributions.. You does not know the
meaning of open contributions.. And you said 2 week ago I complete
hacktoberfest? Are you such a fool person? 🤣

**Comment by 0xScratch** [comment]
That just shows your naivety, nothing else

**Comment by AnkushjainAj** [comment]
Okay.. Don't message again😂

**Comment by 0xScratch** [comment]
> I think you making fool as a open contributions.. You does not know the meaning of open contributions.. And you said 2 week ago I complete hacktoberfest? Are you such a fool person? 🤣

Saw your profile and better I really don't message you again 🤣
Well, have a look -> https://www.holopin.io/@aryan9592#badges

It's just your ego got hit up..and that leaded you to say some things which even you aren't aware of.
If you are feeling like every open-source contribution is a grand one, you are clearly wrong. Many are based on fixes and some minor updations even in some big projects. Not my fault that you are just starting it out and being delusional that open-source contributions always add up in striking some freaking big changes in a repo.
Unsubscribing this conversation...so that your messages won't reach me and I be away from some dumbfucks.

**Comment by AnkushjainAj** [comment]
Okay.. Well done🙂

**Pull request closed without merging**
